# Generated by Django 3.2.8 on 2021-10-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
