# Generated by Django 3.2.8 on 2021-10-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition_app', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
