# Generated by Django 3.2.8 on 2021-10-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition_app', '0004_art_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
