# Generated by Django 3.2.8 on 2021-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition_app', '0008_alter_exhibition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.DateField(verbose_name=['%Y-%M-%D']),
        ),
    ]
